# --------------------------------------------------------
# Octree-based Sparse Convolutional Neural Networks
# Copyright (c) 2022 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train
  best_val: max:mIoU

  logdir: logs/ae_shapenet/ae
  max_epoch: 300
  test_every_epoch: 20
  log_per_iter: 50
  ckpt_num: 20

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: poly
  milestones: (160,240)

DATA:
  train:
    name: shapenet
    points_scale: 128

    # octree building
    depth: 6
    full_depth: 2

    # no data augmentations
    distort: False

    # data loading
    location: data/ae_shapenet/shape.npz
    filelist: data/ae_shapenet/filelist_train.npz.txt
    batch_size: 32
    shuffle: True
    # num_workers: 0

  test:
    name: shapenet
    points_scale: 128

    # octree building
    depth: 6
    full_depth: 2

    # no data augmentations
    distort: False

    # data loading
    location: data/ae_shapenet/shape.npz
    filelist: data/ae_shapenet/filelist_test.npz.txt
    batch_size: 16
    shuffle: False
    # num_workers: 0

MODEL:
  name: autoencoder
  feature: ND   # N -> Normal (3 channels); D -> Local displacement (1 channel)
  channel: 4
  nout: 4
  depth: 6
  full_depth: 2
