SOLVER:
  gpu: 0,
  run: train
  type: sgd

  logdir: logs/m40/m40
  max_epoch: 300
  test_every_epoch: 5

  # lr_type: cos
  weight_decay: 0.0005
  step_size: (120,180,240)
  ckpt_num: 20

DATA:
  train:
    # octree building
    depth: 5
    full_depth: 2

    # transformation
    orient_normal: xyz

    # data augmentations
    distort: True
    angle: (0, 0, 5)      # small rotation along z axis
    interval: (1, 1, 1)
    scale: 0.25
    jitter: 0.125

    # data loading
    location: data/ModelNet40/ModelNet40.ply.normalize
    filelist: data/ModelNet40/filelist/m40_train.txt
    batch_size: 32
    shuffle: True
    # num_workers: 0

  test:
    # octree building
    depth: 5
    full_depth: 2

    # transformation
    orient_normal: xyz
  
    # data augmentations
    distort: False
    angle: (0, 0, 5)      # small rotation along z axis
    interval: (1, 1, 1)
    scale: 0.25
    jitter: 0.125

    # data loading
    location: data/ModelNet40/ModelNet40.ply.normalize
    filelist: data/ModelNet40/filelist/m40_test.txt
    batch_size: 32
    shuffle: False
    # num_workers: 0

MODEL:
  name: lenet
  feature: ND   # N -> Normal (3 channels); D -> Local displacement (1 channel)
  stages: 3
  channel: 4
  nout: 40

LOSS:
  num_class: 40